### ISSUE TITLE
Add correction page for a specific solution ID

### ISSUE THREAD

**Issue by leMaik** [Welfenlab/tutor-corrector#14]
A page like `/correction/by-solution/id` should open the correction page for the solution with the given ID. This is needed to allow correcting specific solutions, as needed if clicking an item in the list of unfinished corrections (see #12).

This should only work if the correction is locked by the current user, see #15!

**Comment by leMaik** [comment]
#15 for your clicking pleasure (can't link that above for some reason).

**Comment by LittleHelicase** [comment]
You can get it by `/api/solution/:id`. There is no separate correction object. Corrections don't have IDs, only solutions. All correction methods give you solution objects.

I don't think that we need a security feature for this.

**Comment by leMaik** [comment]
I didn't mean the API, I just want to add this as a page to the tutor app. No API work to be done here (hence no API label set).

:warning: If we don't have a security feature for this, a tutor could change the correction of another tutor if he knows the ID of the solution.

**Comment by leMaik** [comment]
Discussed security considerations, they're irrelevant. So this is implemented (and fixed today) and already used in the lecturer to allow editing solutions.
