### ISSUE TITLE
Add API request to get a correction by ID

### ISSUE THREAD

**Issue by leMaik** [Welfenlab/tutor-corrector#15]
For #14, we need to get a correction by its ID. I'd suggest `/api/correction/unfinished/:id` as URL. It should only (!) return the correction if it is locked by the current user.

The current `/api/correction/unfinished/:exercise` request is not needed and should be renamed to `/api/correction/exercises/:exercise/unfinished`, which is more meaningful. 
Optional: Also, `.../finished/:exercise` and `.../next/:exercise` should be renamed to fit this new convention.

**Comment by LittleHelicase** [comment]
You can use `/api/solutions/:id` for that like in #14. Again I don't think we need to secure the calls for Tutors.

**Comment by leMaik** [comment]
That request doesn't work, it says `Could not find a group for user with ID max`.#
Does a solution already contain the correction? See my comment in #14 for security concerns.

**Comment by leMaik** [comment]
Okay, closing this now. See #17 for the bug I described above. Would be great if we could try to reproduce that tomorrow. :)
