### ISSUE TITLE
Unfinished corrections should contain the lock date

### ISSUE THREAD

**Issue by leMaik** [Welfenlab/tutor-corrector#16]
Currently, the solution object only contains he locking tutor, not the date. The database already supports this (see Welfenlab/tutor-rethinkdb-database#5). This is needed for #12, I'd suggest `lockDate` as field name.
The database should already have this as of Welfenlab/tutor-rethinkdb-database#5

**Comment by 5cript** [comment]
There should be a field now for locked solutions called 'lockTimeStamp', which is obviously created when the lock is done.

Should not be an issue anymore.

**Comment by 5cript** [comment]
I close this for now, please reopen if issues arise.
