### ISSUE TITLE
Make authorization work with dummy-auth >0.1.7

### ISSUE THREAD

**Issue by leMaik** [Welfenlab/tutor-corrector#21]
Due to changes in tutor-dummy-auth, the authorization only works with dummy-auth 0.1.7.

**Comment by LittleHelicase** [comment]
I think I fixed it in 50b2c4d1cf1f8d8aa0be8201c436d071e4ed22ca . I created a "non-dummy" auth package [@tutor/auth](https://github.com/Welfenlab/tutor-auth). I will test it in production mode soon.

**Comment by LittleHelicase** [comment]
It works in production!
