### ISSUE TITLE
Undo / Redo support

### ISSUE THREAD

**Issue by LittleHelicase** [Welfenlab/tutor-corrector#3]
In the correction interface CTRL+Z / CTRL+SHIRT+Z should work as expected. Remove the last drawn line / text. I would assume it would be something like "remove last element from element list and put it into redo buffer". Redo "take thing from redo buffer and put it back". Every normal action invalidates the redo buffer.

**Comment by leMaik** [comment]
As soon as https://github.com/leMaik/scribble.js/issues/1 is done.

**Comment by leMaik** [comment]
For non-developers (on windows), CTRL+Y is pretty common to undo things. I'll implement both combinations.

**Comment by leMaik** [comment]
I just broke it in 7daf5a0, will fix this later by adding a custom "undo stack" that supports multiple scribble instances.
