### ISSUE TITLE
Choosing a different tool should deactivate text tool

### ISSUE THREAD

**Issue by LittleHelicase** [Welfenlab/tutor-corrector#4]
When the text tool is still active (no Enter key was pressed) one can change the tool which starts drawing undefined texts. The text tool should be deactivated when the tool is changed.

**Comment by leMaik** [comment]
This is a bug in ~~sketch.js~~ scribble.js and should be reported there. :wink: It's now here: https://github.com/leMaik/scribble.js/issues/2 (I had to duplicate the repo to have an issue tracker.)

**Comment by leMaik** [comment]
Just saw that the forked sketch.js doesn't have its own issue tracker... yet.
