### ISSUE TITLE
The color buttons should indicate which one is selected

### ISSUE THREAD

**Issue by LittleHelicase** [Welfenlab/tutor-corrector#5]
I cannot distinguish what color I'm using, when I choose a color it looks like a not selected one.

![image](https://cloud.githubusercontent.com/assets/5698911/10245266/31d74aa6-6906-11e5-8cbf-093492628040.png)

**Comment by leMaik** [comment]
Cannot reproduce, looks like this for me (and it's explicitly coded to do so already):
![bildschirmfoto vom 2015-10-02 13 06 53](https://cloud.githubusercontent.com/assets/5544859/10245294/803013b8-6906-11e5-9497-dfbf092b0f3f.png)

**Comment by LittleHelicase** [comment]
Chrome tells me, that the green class sets a green box-shadow that creates the green border

![image](https://cloud.githubusercontent.com/assets/5698911/10245415/9ca27166-6907-11e5-9d11-1ff1555beec4.png)

**Comment by leMaik** [comment]
~~This _does_ work in Chrome. Latest commit, just tested. Are you sure that you are on the correct branch?~~ Latest Semantic-UI version made active and inactive basic buttons look the same.

**Comment by LittleHelicase** [comment]
I checked twice, I'm confident. I also checked that I have the latest Semantic-UI version (2.1.4).

**Comment by leMaik** [comment]
Yes, I checked that too just a moment ago. My bad, see my edit above...
