### ISSUE TITLE
Keep color when changing the tool

### ISSUE THREAD

**Issue by LittleHelicase** [Welfenlab/tutor-corrector#6]
Currently the color changes back to red when one changes the tool. This should persist (I guess). It felt wrong.

![corrector](https://cloud.githubusercontent.com/assets/5698911/10249707/02e0b11c-6927-11e5-9830-5da86f199eec.gif)

**Comment by leMaik** [comment]
This is a feature, not a bug. Who wants to write in yellow or highlight 
text in red? I assumed that in most cases, the correctors would write 
red and highlight text in yellow, so the color is selected automatically.

**Comment by leMaik** [comment]
Okay, seeing it now I agree that this behaviour _does_ feel strange.
