### ISSUE TITLE
Make Toolbar always visible

### ISSUE THREAD

**Issue by LittleHelicase** [Welfenlab/tutor-corrector#7]
When editing a document the toolbar is fixed above the PDF file. But when you scroll down you cannot use the toolbar anymore.

![scroll](https://cloud.githubusercontent.com/assets/5698911/10249785/6cd18330-6927-11e5-8cf8-1a916ce6b221.gif)

**Comment by leMaik** [comment]
Beautiful CSS animation inclusive. :-)
